#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""
import sys
import math

def is_prime(num):
    if num < 2:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    for i in range(3, int(math.sqrt(num)) + 1, 2):
        if num % i == 0:
            return False
    return True

def factorize():
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line_number in f:
                line_number = int(line_number)
                if line_number < 2:
                    print(f"{line_number} is not factorizable.")
                else:
                    for i in range(2, line_number):
                        if line_number % i == 0:
                            if is_prime(i) and is_prime(line_number // i):
                                print(f"{line_number}={i}*{line_number // i}")
                            break
    except (IndexError, FileNotFoundError):
        pass

factorize()
